server.port=8080
spring.security.oauth2.client.registration.cognito.client-id = ${CLIENT_ID}
spring.security.oauth2.client.registration.cognito.client-secret = ${CLIENT_SECRET}
spring.security.oauth2.client.registration.cognito.scope = openid
spring.security.oauth2.client.registration.cognito.redirect-uri = ${REDIRECT_URI}
spring.security.oauth2.client.registration.cognito.clientName = ${CLIENT_NAME}
spring.security.oauth2.client.registration.cognito.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.cognito.issuerUri = ${ISSUER_URI}
aws.cognito.logoutUrl=${LOGOUT_URL}
aws.cognito.logout.success.redirectUrl=${REDIRECT_URL}